brcm-patchram-plus: fix parser callback type
Newer GCC versions interpret the empty callback parameter list as void.
This causes incompatible pointer type errors for all parser callbacks and
a "too many arguments to function" error when optarg is passed.

Declare the callback type with its expected char *optarg argument.

Fixes:
  brcm_patchram_plus.c:453:25: error: initialization of 'int (*)(void)'
  from incompatible pointer type 'int (*)(char *)'
  brcm_patchram_plus.c:493:40: error: too many arguments to function
  'parse[option_index]'; expected 0, have 1

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>